export { default as Home } from './Home'
export { default as Login } from './Login/Login'
export { default as Transfer } from './Transfer/Transfer'
export { default as Extrato } from './Extrato/Extrato'
export { default as Erro } from './Erro/Erro'